[package]
name = "zap_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
zap_core = { path = "../zap_core" }

[dev-dependencies]
criterion = "0.4"

# [[bench]]
# name = "zap_server_bench"
# harness = false
